export const COUNTRY_STATIC = [
  { name: "India", id: "india", flag: "🇮🇳" },
  { name: "China", id: "china", flag: "🇨🇳" },
  { name: "United States", id: "unitedstates", flag: "🇺🇸" },
  { name: "Indonesia", id: "indonesia", flag: "🇮🇩" },
  { name: "Pakistan", id: "pakistan", flag: "🇵🇰" },
  { name: "Nigeria", id: "nigeria", flag: "🇳🇬" },
  { name: "Brazil", id: "brazil", flag: "🇧🇷" },
  { name: "Bangladesh", id: "bangladesh", flag: "🇧🇩" },
  { name: "Russia", id: "russia", flag: "🇷🇺" },
  { name: "Mexico", id: "mexico", flag: "🇲🇽" },
  { name: "Ethiopia", id: "ethiopia", flag: "🇪🇹" },
  { name: "Japan", id: "japan", flag: "🇯🇵" },
  { name: "Philippines", id: "philippines", flag: "🇵🇭" },
  { name: "Egypt", id: "egypt", flag: "🇪🇬" },
  { name: "DR Congo", id: "drcongo", flag: "🇨🇩" },
  { name: "Vietnam", id: "vietnam", flag: "🇻🇳" },
  { name: "Iran", id: "iran", flag: "🇮🇷" },
  { name: "Turkey", id: "turkey", flag: "🇹🇷" },
  { name: "Germany", id: "germany", flag: "🇩🇪" },
  { name: "Thailand", id: "thailand", flag: "🇹🇭" },
  { name: "United Kingdom", id: "unitedkingdom", flag: "🇬🇧" },
  { name: "Tanzania", id: "tanzania", flag: "🇹🇿" },
  { name: "France", id: "france", flag: "🇫🇷" },
  { name: "South Africa", id: "southafrica", flag: "🇿🇦" },
  { name: "Italy", id: "italy", flag: "🇮🇹" },
  { name: "Kenya", id: "kenya", flag: "🇰🇪" },
  { name: "Myanmar", id: "myanmar", flag: "🇲🇲" },
  { name: "Colombia", id: "colombia", flag: "🇨🇴" },
  { name: "South Korea", id: "southkorea", flag: "🇰🇷" },
  { name: "Uganda", id: "uganda", flag: "🇺🇬" },
  { name: "Sudan", id: "sudan", flag: "🇸🇩" },
  { name: "Spain", id: "spain", flag: "🇪🇸" },
  { name: "Argentina", id: "argentina", flag: "🇦🇷" },
  { name: "Algeria", id: "algeria", flag: "🇩🇿" },
  { name: "Iraq", id: "iraq", flag: "🇮🇶" },
  { name: "Afghanistan", id: "afghanistan", flag: "🇦🇫" },
  { name: "Poland", id: "poland", flag: "🇵🇱" },
  { name: "Canada", id: "canada", flag: "🇨🇦" },
  { name: "Morocco", id: "morocco", flag: "🇲🇦" },
  { name: "Saudi Arabia", id: "saudiarabia", flag: "🇸🇦" },
  { name: "Ukraine", id: "ukraine", flag: "🇺🇦" },
  { name: "Angola", id: "angola", flag: "🇦🇴" },
  { name: "Uzbekistan", id: "uzbekistan", flag: "🇺🇿" },
  { name: "Yemen", id: "yemen", flag: "🇾🇪" },
  { name: "Peru", id: "peru", flag: "🇵🇪" },
  { name: "Malaysia", id: "malaysia", flag: "🇲🇾" },
  { name: "Ghana", id: "ghana", flag: "🇬🇭" },
  { name: "Mozambique", id: "mozambique", flag: "🇲🇿" },
  { name: "Nepal", id: "nepal", flag: "🇳🇵" },
  { name: "Madagascar", id: "madagascar", flag: "🇲🇬" },
  { name: "Ivory Coast", id: "ivorycoast", flag: "🇨🇮" },
  { name: "Venezuela", id: "venezuela", flag: "🇻🇪" },
  { name: "Cameroon", id: "cameroon", flag: "🇨🇲" },
  { name: "Australia", id: "australia", flag: "🇦🇺" },
  { name: "North Korea", id: "northkorea", flag: "🇰🇵" },
  { name: "Taiwan", id: "taiwan", flag: "🇹🇼" },
  { name: "Mali", id: "mali", flag: "🇲🇱" },
  { name: "Burkina Faso", id: "burkinafaso", flag: "🇧🇫" },
  { name: "Syria", id: "syria", flag: "🇸🇾" },
  { name: "Sri Lanka", id: "srilanka", flag: "🇱🇰" },
  { name: "Malawi", id: "malawi", flag: "🇲🇼" },
  { name: "Zambia", id: "zambia", flag: "🇿🇲" },
  { name: "Romania", id: "romania", flag: "🇷🇴" },
  { name: "Chile", id: "chile", flag: "🇨🇱" },
  { name: "Kazakhstan", id: "kazakhstan", flag: "🇰🇿" },
  { name: "Chad", id: "chad", flag: "🇹🇩" },
  { name: "Ecuador", id: "ecuador", flag: "🇪🇨" },
  { name: "Somalia", id: "somalia", flag: "🇸🇴" },
  { name: "Guatemala", id: "guatemala", flag: "🇬🇹" },
  { name: "Senegal", id: "senegal", flag: "🇸🇳" },
  { name: "Netherlands", id: "netherlands", flag: "🇳🇱" },
  { name: "Cambodia", id: "cambodia", flag: "🇰🇭" },
  { name: "Zimbabwe", id: "zimbabwe", flag: "🇿🇼" },
  { name: "Guinea", id: "guinea", flag: "🇬🇳" },
  { name: "Rwanda", id: "rwanda", flag: "🇷🇼" },
  { name: "Benin", id: "benin", flag: "🇧🇯" },
  { name: "Burundi", id: "burundi", flag: "🇧🇮" },
  { name: "Tunisia", id: "tunisia", flag: "🇹🇳" },
  { name: "Bolivia", id: "bolivia", flag: "🇧🇴" },
  { name: "Belgium", id: "belgium", flag: "🇧🇪" },
  { name: "Haiti", id: "haiti", flag: "🇭🇹" },
  { name: "Cuba", id: "cuba", flag: "🇨🇺" },
  { name: "South Sudan", id: "southsudan", flag: "🇸🇸" },
  { name: "Dominican Republic", id: "dominicanrepublic", flag: "🇩🇴" },
  { name: "Czech Republic", id: "czechrepublic", flag: "🇨🇿" },
  { name: "Greece", id: "greece", flag: "🇬🇷" },
  { name: "Jordan", id: "jordan", flag: "🇯🇴" },
  { name: "Portugal", id: "portugal", flag: "🇵🇹" },
  { name: "Azerbaijan", id: "azerbaijan", flag: "🇦🇿" },
  { name: "Sweden", id: "sweden", flag: "🇸🇪" },
  { name: "Honduras", id: "honduras", flag: "🇭🇳" },
  { name: "United Arab Emirates", id: "unitedarabemirates", flag: "🇦🇪" },
  { name: "Hungary", id: "hungary", flag: "🇭🇺" },
  { name: "Tajikistan", id: "tajikistan", flag: "🇹🇯" },
  { name: "Belarus", id: "belarus", flag: "🇧🇾" },
  { name: "Austria", id: "austria", flag: "🇦🇹" },
  { name: "Papua New Guinea", id: "papuanewguinea", flag: "🇵🇬" },
  { name: "Serbia", id: "serbia", flag: "🇷🇸" },
  { name: "Israel", id: "israel", flag: "🇮🇱" },
  { name: "Switzerland", id: "switzerland", flag: "🇨🇭" },
];
